name: PlayerNotes
version: 1.4
author: pmme
description: Allow staff to store and retrieve player notes in-game.
main: nz.pmme.playernotes.PlayerNotes

commands:
  playernotes:
    description: PlayerNotes commands
    usage: /playernotes <create|new|view|viewall|viewby|viewallbook|vab|dispose|del|delplayer|delall>
    aliases: pn

permissions:
  playernotes.create:
    description: Allows creation of player notes.
    default: op
  playernotes.view:
    description: Allows viewing player notes.
    default: op
  playernotes.book:
    description: Allows viewing player notes in a book. Books can be dropped. Not so safe.
    default: op
  playernotes.delete:
    description: Allows deletion of player notes.
    default: op
  playernotes.deleteall:
    description: Allows delection of all player notes.
    default: op
